### ISSUE TITLE
Error:  String indices must be integers

### ISSUE THREAD

**Issue by alpertoruun** [szn/confluence.md#15] opened 2024-02-27 12:23 UTC
When I try to updating my page on atlassion, I get this error
 -> confluence.md -u alper --token NDcwN  update --file deneme.md --page_id 15 --url https://confluence.xx.net
15:02:58 >  Updates page content based on given page_id or metadata in Markdown file        
15:02:04 > string indices must be integers
Why I get these error?

**Comment by szn** [comment] 2024-02-27 12:26
Hi @alpertoruun,

Can you please run it again with `-v` flag?

Also, `.md` file content is welcome (feel free to remove sensitive data, but leave as much content as possible)

**Comment by alpertoruun** [comment] 2024-02-27 12:30
When I ran the command with -v : 
15:02:30 >  Updates page content based on given page_id or metadata in Markdown file        
15:02:30 > Updating page `xxxx` based on `md_file` file
15:02:30 > Converting MD to HTML
15:02:30 > Getting list of images from MD file
15:02:30 > Getting list of images from MD file
15:02:30 > Getting page title from page id `xxxxx`
15:02:33 > **string indices must be integers**

my .md file:
## 1.1 Pipeline Configuration Overview

### 1.1.1 Description

The pipeline configuration includes several key components designed to enhance functionality, manage dependencies, and streamline processes. Each component plays a crucial role in ensuring the smooth execution of the pipeline.

### 1.1.2 Included Configuration Files

The pipeline configuration leverages modularization by including various configuration files from a centralized location. These files contribute to different aspects of the pipeline:

1. **Show Dependencies**
   - Provides transparency into project dependencies.
   - Configuration file: [.show-dependencies.yml](https://xxxxxxx) .......

**Comment by szn** [comment] 2024-02-27 14:14
Well, github comments support markdown. So your file was converted into HTML ;).

I am still lost, thus another request:

Please upgrade the package to the latest version (it should be `v0.2.9`) with:

```
python -m pip install  --upgrade confluence.md
```

Then run the same command with `-v` flag again. Copy the output along with your `.md` file BUT please do so within code block:

```
 ```
 (output – please remove the spaces betore the ``` ticks)
 ```
```

**Comment by alpertoruun** [comment] 2024-02-27 14:22
@szn 
I upgraded to the latest version and ran again;
 ```
confluence.md -u alper --token NDcwND update --file deneme.md --page_id 15 --url https://confluence.xxx.net -v

 ```

 My Md files:
  ```
## 1.1 Pipeline Configuration Overview

### 1.1.1 Description

The pipeline configuration includes several key components designed to enhance functionality, manage dependencies, and streamline processes. Each component plays a crucial role in ensuring the smooth execution of the pipeline.

### 1.1.2 Included Configuration Files

The pipeline configuration leverages modularization by including various configuration files from a centralized location. These files contribute to different aspects of the pipeline:

1. **Show Dependencies**
   - Provides transparency into project dependencies.
   - Configuration file: [.show-dependencies.yml](https://xxxxxx.yml)

 ```

**Comment by alpertoruun** [comment] 2024-02-27 14:46
@szn  I think, this error is not related to md files. I used your md files and got same error again

**Comment by szn** [comment] 2024-02-27 14:55
You are right @alpertoruun, but I wanted to be sure.

I can see is the official Atlassian `get_page_by_id` method returns a string, instead of an object. 

This time I added some extra checks in this exact spot. I pushed it into test-pypi repository. You can upgrade with:

```
python -m pip install --index-url https://test.pypi.org/simple/ --upgrade confluence.md
```

So, excuse the inconvenience but I am asking you to repeat the procedure using `v0.2.10`.

**Comment by alpertoruun** [comment] 2024-02-27 15:20
@szn 
I tried v0.2.10. I think, error related to authentication
result:
```
https://confluence.piworks.net -v
17:02:43 >  Updates page content based on given page_id or metadata in Markdown file        
17:02:43 > Updating page `xxxx` based on `md_file` file
17:02:43 > Converting MD to HTML
17:02:43 > Getting list of images from MD file
17:02:43 > Getting list of images from MD file
17:02:43 > Getting page title from page id `xxxx`


<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">
<head>
    <title>Sign in to your account</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <link rel="preconnect" href="https://aadcdn.msauth.net" crossorigin>
<meta http-equiv="x-dns-prefetch-control" content="on">
<link rel="dns-prefetch" href="//aadcdn.msauth.net">
<link rel="dns-prefetch" href="//aadcdn.msftauth.net">

    <meta name="PageID" content="ConvergedSignIn" />
    <meta name="SiteID" content="" />
    <meta name="ReqLC" content="1033" />
    <meta name="LocLC" content="en-US" />

        <meta name="referrer" content="origin" />

        <meta name="format-detection" content="telephone=no" />

    <noscript>
        <meta http-equiv="Refresh" content="0; URL=https://login.microsoftonline.com/jsdisabled" />
    </noscript>



<meta name="robots" content="none" />

<script type="text/javascript">//<![CDATA[........

<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">
<head>
    <title>Sign in to your account</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <link rel="preconnect" href="https://aadcdn.msauth.net" crossorigin>
<meta http-equiv="x-dns-prefetch-control" content="on">
<link rel="dns-prefetch" href="//aadcdn.msauth.net">
<link rel="dns-prefetch" href="//aadcdn.msftauth.net">

    <meta name="PageID" content="ConvergedSignIn" />
    <meta name="SiteID" content="" />
    <meta name="ReqLC" content="1033" />
    <meta name="LocLC" content="en-US" />

        <meta name="referrer" content="origin" />

        <meta name="format-detection" content="telephone=no" />

    <noscript>
        <meta http-equiv="Refresh" content="0; URL=https://login.microsoftonline.com/jsdisabled" />
    </noscript>



<meta name="robots" content="none" />

<script type="text/javascript">//<![CDATA[
 <title>Sign in to your account</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <link rel="preconnect" href="https://aadcdn.msauth.net" crossorigin>
<meta http-equiv="x-dns-prefetch-control" content="on">
<link rel="dns-prefetch" href="//aadcdn.msauth.net">
<link rel="dns-prefetch" href="//aadcdn.msftauth.net">

    <meta name="PageID" content="ConvergedSignIn" />
    <meta name="SiteID" content="" />
    <meta name="ReqLC" content="1033" />
    <meta name="LocLC" content="en-US" />

        <meta name="referrer" content="origin" />

        <meta name="format-detection" content="telephone=no" />

    <noscript>
        <meta http-equiv="Refresh" content="0; URL=https://login.microsoftonline.com/jsdisabled" />
    </noscript>



<meta name="robots" content="none" />
,"showCantAccessAccountLink":true,"urlGitHubFed":"https://login.live.com/oauth20_authorize.srf?scope=openid+profile+email+offli.
```
I can acces to https://confluence.xxxx.net

**Comment by alpertoruun** [comment] 2024-03-01 06:43
@szn 
sorry, this was my mistake in dns setting of wsl but  It doesnt still run. Another tool runs this token.
```
confluence.md --user xxx --token NDcwND update --file docs/deneme.md --page_id 1534 --url 
https://confluence.piworks.net -v
09:03:42 >  Updates page content based on given page_id or metadata in Markdown file        
09:03:42 > Updating page `xxxx` based on `md_file` file
09:03:42 > Converting MD to HTML
09:03:42 > Getting list of images from MD file
09:03:42 > Getting list of images from MD file
09:03:42 > Getting page title from page id `xxx`
09:03:42 > Unauthorized (401)
Traceback (most recent call last):
  File "/home/alper/.local/bin/confluence.md", line 8, in <module>
    sys.exit(main())
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/main.py", line 140, in main
    raise error
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/main.py", line 136, in main
    globals()[args.action](args)
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/main.py", line 15, in wrapper
    function(args)
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/main.py", line 29, in update
    confluence.update_existing(args.page_id)
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/utils/confluencemd.py", line 104, in update_existing
    title = self.get_page_title_by_id(page_id)
  File "/home/alper/.local/lib/python3.10/site-packages/md2cf/utils/confluencemd.py", line 212, in get_page_title_by_id
    page = self.get_page_by_id(page_id)
  File "/home/alper/.local/lib/python3.10/site-packages/atlassian/confluence.py", line 346, in get_page_by_id
    response = self.get(url, params=params)
  File "/home/alper/.local/lib/python3.10/site-packages/atlassian/rest_client.py", line 340, in get
    response = self.request(
  File "/home/alper/.local/lib/python3.10/site-packages/atlassian/rest_client.py", line 312, in request
    self.raise_for_status(response)
  File "/home/alper/.local/lib/python3.10/site-packages/atlassian/confluence.py", line 3261, in raise_for_status
    raise HTTPError("Unauthorized (401)", response=response)
requests.exceptions.HTTPError: Unauthorized (401)
```

**Comment by szn** [comment] 2024-04-10 15:54
Excuse late reply. Can you confirm, that `curl` request from my Feb 27th works while `confluence.md` doesn't?

**Comment by szn** [comment] 2024-09-17 16:42
Closing – can't reproduce.

**Closed by szn** 2024-09-17 16:42 UTC
